# Generated by Django 4.0.2 on 2022-02-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaldetect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointgroup',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pointgroup',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
