# Generated by Django 4.0.2 on 2022-02-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metaldetect', '0004_atrifacttype_event_period_alter_point_group_artifact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AtrifactType',
            new_name='ArtifactType',
        ),
    ]
