# Generated by Django 4.0.2 on 2022-02-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaldetect', '0006_artifactphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='photos',
            field=models.ManyToManyField(to='metaldetect.ArtifactPhoto'),
        ),
    ]
